<?php
global $opt_name,$theme_text_domain;

Redux::setSection( $opt_name, array(
    'title'  => esc_html__( 'Print Property', $theme_text_domain ),
    'id'     => 'property-print',
    'desc'   => '',
    'icon'   => 'el-icon-print el-icon-small',
    'fields'        => array(
        array(
            'id'        => 'print_page_logo',
            'url'       => true,
            'type'      => 'media',
            'title'     => esc_html__( 'Print Property Logo', $theme_text_domain ),
            'read-only' => false,
            'default'   => array( 'url' => YANI_THEME_IMAGES .'logo-houzez-color.png' ),
            'subtitle'  => esc_html__( 'Upload your custom site logo for print property.', $theme_text_domain ),
        ),
        array(
            'id'       => 'print_agent',
            'type'     => 'switch',
            'title'    => esc_html__( 'Property Agent', $theme_text_domain ),
            'desc'     => '',
            'subtitle' => '',
            'default'  => 1,
            'on'       => esc_html__( 'Yes', $theme_text_domain ),
            'off'      => esc_html__( 'No', $theme_text_domain ),
        ),
        array(
            'id'       => 'print_description',
            'type'     => 'switch',
            'title'    => esc_html__( 'Property Description', $theme_text_domain ),
            'desc'     => '',
            'subtitle' => '',
            'default'  => 1,
            'on'       => esc_html__( 'Yes', $theme_text_domain ),
            'off'      => esc_html__( 'No', $theme_text_domain ),
        ),
        array(
            'id'       => 'print_details',
            'type'     => 'switch',
            'title'    => esc_html__( 'Property Details', $theme_text_domain ),
            'desc'     => '',
            'subtitle' => '',
            'default'  => 1,
            'on'       => esc_html__( 'Yes', $theme_text_domain ),
            'off'      => esc_html__( 'No', $theme_text_domain ),
        ),
        array(
            'id'       => 'print_features',
            'type'     => 'switch',
            'title'    => esc_html__( 'Property Features', $theme_text_domain ),
            'desc'     => '',
            'subtitle' => '',
            'default'  => 1,
            'on'       => esc_html__( 'Yes', $theme_text_domain ),
            'off'      => esc_html__( 'No', $theme_text_domain ),
        ),
        array(
            'id'       => 'print_energy_class',
            'type'     => 'switch',
            'title'    => esc_html__( 'Energy Class', $theme_text_domain ),
            'desc'     => '',
            'subtitle' => '',
            'default'  => 1,
            'on'       => esc_html__( 'Yes', $theme_text_domain ),
            'off'      => esc_html__( 'No', $theme_text_domain ),
        ),
        array(
            'id'       => 'print_floorplans',
            'type'     => 'switch',
            'title'    => esc_html__( 'Floor Plans', $theme_text_domain ),
            'desc'     => '',
            'subtitle' => '',
            'default'  => 1,
            'on'       => esc_html__( 'Yes', $theme_text_domain ),
            'off'      => esc_html__( 'No', $theme_text_domain ),
        ),
        array(
            'id'       => 'print_gallery',
            'type'     => 'switch',
            'title'    => esc_html__( 'Gallery Images', $theme_text_domain ),
            'desc'     => '',
            'subtitle' => '',
            'default'  => 0,
            'on'       => esc_html__( 'Yes', $theme_text_domain ),
            'off'      => esc_html__( 'No', $theme_text_domain ),
        ),
        array(
            'id'       => 'print_gr_code',
            'type'     => 'switch',
            'title'    => esc_html__( 'QR Code', $theme_text_domain ),
            'desc'     => '',
            'subtitle' => '',
            'default'  => 1,
            'on'       => esc_html__( 'Yes', $theme_text_domain ),
            'off'      => esc_html__( 'No', $theme_text_domain ),
        ),
    )
));